const designTokens = require('./src/lib/designTokens.json')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/**/*.html', './src/**/*.{js,jsx,ts,tsx}'],
  future: {
    hoverOnlyWhenSupported: true,
  },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'accents-0': 'var(--accents-0)',
        'accents-1': 'var(--accents-1)',
        'accents-2': 'var(--accents-2)',
        black: 'var(--black)',
        blue: 'var(--blue)',
        brown: 'var(--brown)',
        cadetGreen: 'var(--cadetGreen)',
        chalkWhite: 'var(--chalkWhite)',
        charcoal: 'var(--charcoal)',
        chocolate: 'var(--chocolate)',
        cinderMarl: 'var(--cinderMarl)',
        cyan: 'var(--cyan)',
        deepOcean: 'var(--deepOcean)',
        green: 'var(--green)',
        grey: 'var(--grey)',
        greyMarl: 'var(--greyMarl)',
        hover: 'var(--hover)',
        'hover-1': 'var(--hover-1)',
        'hover-2': 'var(--hover-2)',
        ink: 'var(--ink)',
        ivory: 'var(--ivory)',
        lightGrey: 'var(--lightGrey)',
        lightGreyMarl: 'var(--lightGreyMarl)',
        military: 'var(--military)',
        nights: 'var(--nights)',
        oliveGreen: 'var(--oliveGreen)',
        opticWhite: 'var(--opticWhite)',
        pink: 'var(--pink)',
        primary: 'var(--primary)',
        'primary-2': 'var(--primary-2)',
        putty: 'var(--putty)',
        red: 'var(--red)',
        secondary: 'var(--secondary)',
        'secondary-2': 'var(--secondary-2)',
        taupe: 'var(--taupe)',
        taupeMarl: 'var(--taupeMarl)',
        tempestBlue: 'var(--tempestBlue)',
        vintageBlack: 'var(--vintageBlack)',
        violet: 'var(--violet)',
        'violet-light': 'var(--violet-light)',
      },
      lineHeight: { 'extra-loose': '2.2' },
      maxWidth: { '8xl': '1920px' },
      outline: { black: '2px solid black', white: '2px solid white' },
      textColor: {
        base: 'var(--text-base)',
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
      },
      width: { '1/2': designTokens.Width.tokens['1/2'].$value },
      boxShadow: { DEFAULT: designTokens.Shadows.tokens.light.$value },
    },
    screens: {
      '2xl': { min: designTokens.Breakpoints.tokens['2xl'].min.$value },
      xl: { max: designTokens.Breakpoints.tokens.xl.max.$value, min: designTokens.Breakpoints.tokens.xl.min.$value },
      lg: { max: designTokens.Breakpoints.tokens.lg.max.$value, min: designTokens.Breakpoints.tokens.lg.min.$value },
      md: { min: designTokens.Breakpoints.tokens.md.min.$value },
      sm: { max: designTokens.Breakpoints.tokens.sm.max.$value },
    },
    fontFamily: {
      body: ['var(--font-inter)', designTokens['Font Family'].tokens.body.$value],
      // TODO remove after upgrading to storybook v7
      sans: designTokens['Font Family'].tokens.body.$value,
    },
    borderRadius: {
      large: designTokens.Radius.tokens.large.$value,
      DEFAULT: designTokens.Radius.tokens.default.$value,
      circle: designTokens.Radius.tokens.circle.$value,
    },
  },
  corePlugins: {
    textOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    placeholderOpacity: false,
    ringOpacity: false,
  },
  important: true,
  variants: { extend: {} },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
}
